# Generated by Django 3.0.8 on 2020-07-28 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='agent_id',
            new_name='username',
        ),
    ]
